name: Delete Scripted Volunteer

on:
  push:
    branches: 
      - "Configure/NamTH/Add_workflow"

jobs:
  Connecting-To-Server-And-Restart:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Configure/NamTH/Add_workflow'
    steps:
    - name: Restarting
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          bash delete_scripted.sh
          echo Server is restarting